services:
  estbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: estbot
    volumes:
      - ./config.secret.json:/app/config.secret.json:ro
      - ./data:/data
    restart: unless-stopped
