name: Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x

    - name: Restore
      run: dotnet restore --ignore-failed-sources

    - name: Publish
      run: dotnet publish src/Automation/Estranged.Automation.csproj --configuration Release --runtime linux-x64 --output build/output
      
    - name: Login to Public ECR
      uses: docker/login-action@v1
      with:
        registry: public.ecr.aws
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Push to ECR
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t public.ecr.aws/j7m3k0v4/estbot:$IMAGE_TAG .
        docker build -t public.ecr.aws/j7m3k0v4/estbot:latest .
        docker push --all-tags public.ecr.aws/j7m3k0v4/estbot
